### ISSUE TITLE
Dont sleep when starting servers prior to running e2e tests in CircleCI

### ISSUE THREAD

**Issue by brian-mann** [withspectrum/spectrum#2828]
**The Problem**

This line right here is unnecessary: https://github.com/withspectrum/spectrum/blob/alpha/.circleci/config.yml#L110

Effectively even if your servers are ready before 60 seconds, it will wait until at least that long. If for some reason they did take **longer** than 60 seconds, Cypress will insta-fail.

**The Solution**

Use an NPM module like this: https://github.com/jeffbski/wait-on

That will allow you to wait on the servers you expect to boot and the moment they're accessible it will move on. Something like this...

```yml
- run: *start-api
- run: *start-web
- run: wait-on http://localhost:3000
- run: wait-on http://the-other-thing
- run:
    name: Run Unit Tests
    command: yarn run test:ci
```
