### ISSUE TITLE
Focusable elements are not focused making it difficult to know what you're interacting with 

### ISSUE THREAD

**Issue by nickcolley** [withspectrum/spectrum#4298]
**Issue Type (check one)**

- [x] Bug Report

**Description (type any text below)** -->

When tabbing through the Spectrum interface it's difficult to know what you're interacting with since the outlines for tabbable elements have been removed.

If you force outlines back on you can see what is being tabbed.

```css
*:focus {
    outline: 3px solid orange !important;
    outline-offset: -2px;
}
```

You might want to consider https://github.com/WICG/focus-visible if you're worried about having too many focus outlines in your interface.
